package com.ayalab.payment.logging;

public enum PaymentEventType {
    PAYMENT_INITIATED,
    PAYMOB_AUTH_SUCCESS,
    PAYMOB_AUTH_FAILED,
    ORDER_REGISTERED,
    PAYMENT_KEY_GENERATED,
    METHOD_EXECUTED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    WEBHOOK_RECEIVED,
    WEBHOOK_VERIFIED,
    WEBHOOK_REJECTED
}
